# Generated by Django 2.2.1 on 2019-07-16 21:48

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdBasePage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.Page',
                    ),
                ),
                ('author', models.CharField(blank=True, max_length=255)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BirdPage',
            fields=[
                (
                    'birdbasepage_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='birdapp657.BirdBasePage',
                    ),
                ),
                (
                    'body',
                    wagtail.fields.StreamField(
                        [
                            (
                                'heading',
                                wagtail.blocks.CharBlock(
                                    classname='full title', required=False
                                ),
                            ),
                            (
                                'paragraph',
                                wagtail.blocks.RichTextBlock(required=False),
                            ),
                            (
                                'image',
                                wagtail.images.blocks.ImageChooserBlock(required=False),
                            ),
                        ]
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=('birdapp657.birdbasepage',),
        ),
    ]
