# Generated by Django 2.2.1 on 2019-08-24 16:05

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp657', '0009_formbirdpage_formfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formbirdpage',
            name='thank_you_text',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
