# Generated by Django 2.2.1 on 2019-09-01 23:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailimages', '0001_squashed_0021'),
        ('birdapp657', '0012_collectionbirdpage_solobirdpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempRawBirdPage',
            new_name='HTMLBirdPage',
        ),
    ]
