# Generated by Django 2.2.1 on 2019-09-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp657', '0015_auto_20190906_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionbirdpage',
            name='show_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formbirdpage',
            name='show_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='htmlbirdpage',
            name='show_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solobirdpage',
            name='show_date',
            field=models.BooleanField(default=False),
        ),
    ]
