# Generated by Django 2.2.1 on 2019-09-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp657', '0017_auto_20190908_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionbirdpage',
            name='show_meta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collectionbirdpage',
            name='show_title',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formbirdpage',
            name='show_meta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formbirdpage',
            name='show_title',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='htmlbirdpage',
            name='show_meta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='htmlbirdpage',
            name='show_title',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='solobirdpage',
            name='show_meta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solobirdpage',
            name='show_title',
            field=models.BooleanField(default=True),
        ),
    ]
