# Generated by Django 2.2.1 on 2019-09-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp657', '0020_auto_20190914_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionbirdpage',
            name='show_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formbirdpage',
            name='show_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='htmlbirdpage',
            name='show_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='searchbirdpage',
            name='show_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='solobirdpage',
            name='show_menu',
            field=models.BooleanField(default=True),
        ),
    ]
