# Generated by Django 2.2.1 on 2019-09-21 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('birdapp657', '0021_auto_20190920_2223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HTMLBirdPage',
        ),
    ]
