# Generated by Django 2.2.1 on 2019-10-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp657', '0023_auto_20191012_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionbirdpage',
            name='exclude_from_sitemap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formbirdpage',
            name='exclude_from_sitemap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchbirdpage',
            name='exclude_from_sitemap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solobirdpage',
            name='exclude_from_sitemap',
            field=models.BooleanField(default=False),
        ),
    ]
