# Generated by Django 2.2.1 on 2019-11-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp657', '0032_auto_20191101_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='formbirdpage',
            name='content_with',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='searchbirdpage',
            name='content_with',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solobirdpage',
            name='content_with',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
