# Generated by Django 2.2.7 on 2019-11-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp657', '0033_auto_20191109_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='show_name',
            field=models.BooleanField(default=True),
        ),
    ]
