# Generated by Django 2.2.7 on 2019-11-24 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('birdapp657', '0034_brandingsettings_show_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='formbirdpage',
            name='hover_menu_icon',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailimages.Image',
            ),
        ),
        migrations.AddField(
            model_name='formbirdpage',
            name='hover_over_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchbirdpage',
            name='hover_menu_icon',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailimages.Image',
            ),
        ),
        migrations.AddField(
            model_name='searchbirdpage',
            name='hover_over_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solobirdpage',
            name='hover_menu_icon',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailimages.Image',
            ),
        ),
        migrations.AddField(
            model_name='solobirdpage',
            name='hover_over_menu',
            field=models.BooleanField(default=False),
        ),
    ]
