# Generated by Django 2.2.7 on 2019-11-26 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('birdapp657', '0036_brandingsettings_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='mobile_menu_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
