# Generated by Django 3.0 on 2020-06-13 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp657', '0055_fontface'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formbirdpage',
            old_name='coverImage',
            new_name='cover_image',
        ),
        migrations.RenameField(
            model_name='searchbirdpage',
            old_name='coverImage',
            new_name='cover_image',
        ),
        migrations.RenameField(
            model_name='solobirdpage',
            old_name='coverImage',
            new_name='cover_image',
        ),
    ]
