# Generated by Django 3.1 on 2020-10-06 19:25

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtailmedia.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp657', '0056_auto_20200613_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='clean_name',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Safe name of the form field, the label converted to ascii_snake_case',
                max_length=255,
                verbose_name='name',
            ),
        ),
        migrations.AlterField(
            model_name='formbirdpage',
            name='header',
            field=wagtail.core.fields.StreamField(
                [
                    (
                        'header',
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    'block_class',
                                    wagtail.core.blocks.CharBlock(
                                        help_text='Block class',
                                        null=True,
                                        required=False,
                                    ),
                                ),
                                (
                                    'muted',
                                    wagtail.core.blocks.BooleanBlock(
                                        default=True, help_text='Muted', required=False
                                    ),
                                ),
                                (
                                    'autoplay',
                                    wagtail.core.blocks.BooleanBlock(
                                        default=False,
                                        help_text='Autoplay',
                                        required=False,
                                    ),
                                ),
                                (
                                    'loop',
                                    wagtail.core.blocks.BooleanBlock(
                                        default=False, help_text='Loop', required=False
                                    ),
                                ),
                                (
                                    'controls',
                                    wagtail.core.blocks.BooleanBlock(
                                        default=True,
                                        help_text='Controls',
                                        required=False,
                                    ),
                                ),
                                (
                                    'block_media',
                                    wagtailmedia.blocks.AbstractMediaChooserBlock(
                                        null=True, required=False
                                    ),
                                ),
                                (
                                    'image',
                                    wagtail.images.blocks.ImageChooserBlock(
                                        null=True, required=False
                                    ),
                                ),
                                (
                                    'font_color',
                                    wagtail.core.blocks.CharBlock(
                                        null=True, required=False
                                    ),
                                ),
                                (
                                    'bg_color',
                                    wagtail.core.blocks.CharBlock(
                                        null=True, required=False
                                    ),
                                ),
                                (
                                    'text_align',
                                    wagtail.core.blocks.CharBlock(
                                        default='left', required=False
                                    ),
                                ),
                                (
                                    'text',
                                    wagtail.core.blocks.RichTextBlock(
                                        features=[
                                            'h1',
                                            'h2',
                                            'h3',
                                            'h4',
                                            'h5',
                                            'bold',
                                            'italic',
                                            'link',
                                            'document-link',
                                            'ol',
                                            'ul',
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    'button_link',
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                'font_color',
                                                wagtail.core.blocks.CharBlock(
                                                    null=True, required=False
                                                ),
                                            ),
                                            (
                                                'bg_color',
                                                wagtail.core.blocks.CharBlock(
                                                    null=True, required=False
                                                ),
                                            ),
                                            (
                                                'page_link',
                                                wagtail.core.blocks.PageChooserBlock(
                                                    help_text='Link to a page.',
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                'external_link',
                                                wagtail.core.blocks.URLBlock(
                                                    help_text='Link to a URL.',
                                                    label='Link URL',
                                                    max_length=200,
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                'text',
                                                wagtail.core.blocks.CharBlock(
                                                    help_text='Link text',
                                                    null=True,
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        null=True,
                                        required=False,
                                    ),
                                ),
                            ],
                            null=True,
                            required=False,
                        ),
                    )
                ],
                blank=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='searchbirdpage',
            name='header',
            field=wagtail.core.fields.StreamField(
                [
                    (
                        'header',
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    'block_class',
                                    wagtail.core.blocks.CharBlock(
                                        help_text='Block class',
                                        null=True,
                                        required=False,
                                    ),
                                ),
                                (
                                    'muted',
                                    wagtail.core.blocks.BooleanBlock(
                                        default=True, help_text='Muted', required=False
                                    ),
                                ),
                                (
                                    'autoplay',
                                    wagtail.core.blocks.BooleanBlock(
                                        default=False,
                                        help_text='Autoplay',
                                        required=False,
                                    ),
                                ),
                                (
                                    'loop',
                                    wagtail.core.blocks.BooleanBlock(
                                        default=False, help_text='Loop', required=False
                                    ),
                                ),
                                (
                                    'controls',
                                    wagtail.core.blocks.BooleanBlock(
                                        default=True,
                                        help_text='Controls',
                                        required=False,
                                    ),
                                ),
                                (
                                    'block_media',
                                    wagtailmedia.blocks.AbstractMediaChooserBlock(
                                        null=True, required=False
                                    ),
                                ),
                                (
                                    'image',
                                    wagtail.images.blocks.ImageChooserBlock(
                                        null=True, required=False
                                    ),
                                ),
                                (
                                    'font_color',
                                    wagtail.core.blocks.CharBlock(
                                        null=True, required=False
                                    ),
                                ),
                                (
                                    'bg_color',
                                    wagtail.core.blocks.CharBlock(
                                        null=True, required=False
                                    ),
                                ),
                                (
                                    'text_align',
                                    wagtail.core.blocks.CharBlock(
                                        default='left', required=False
                                    ),
                                ),
                                (
                                    'text',
                                    wagtail.core.blocks.RichTextBlock(
                                        features=[
                                            'h1',
                                            'h2',
                                            'h3',
                                            'h4',
                                            'h5',
                                            'bold',
                                            'italic',
                                            'link',
                                            'document-link',
                                            'ol',
                                            'ul',
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    'button_link',
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                'font_color',
                                                wagtail.core.blocks.CharBlock(
                                                    null=True, required=False
                                                ),
                                            ),
                                            (
                                                'bg_color',
                                                wagtail.core.blocks.CharBlock(
                                                    null=True, required=False
                                                ),
                                            ),
                                            (
                                                'page_link',
                                                wagtail.core.blocks.PageChooserBlock(
                                                    help_text='Link to a page.',
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                'external_link',
                                                wagtail.core.blocks.URLBlock(
                                                    help_text='Link to a URL.',
                                                    label='Link URL',
                                                    max_length=200,
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                'text',
                                                wagtail.core.blocks.CharBlock(
                                                    help_text='Link text',
                                                    null=True,
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        null=True,
                                        required=False,
                                    ),
                                ),
                            ],
                            null=True,
                            required=False,
                        ),
                    )
                ],
                blank=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='solobirdpage',
            name='header',
            field=wagtail.core.fields.StreamField(
                [
                    (
                        'header',
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    'block_class',
                                    wagtail.core.blocks.CharBlock(
                                        help_text='Block class',
                                        null=True,
                                        required=False,
                                    ),
                                ),
                                (
                                    'muted',
                                    wagtail.core.blocks.BooleanBlock(
                                        default=True, help_text='Muted', required=False
                                    ),
                                ),
                                (
                                    'autoplay',
                                    wagtail.core.blocks.BooleanBlock(
                                        default=False,
                                        help_text='Autoplay',
                                        required=False,
                                    ),
                                ),
                                (
                                    'loop',
                                    wagtail.core.blocks.BooleanBlock(
                                        default=False, help_text='Loop', required=False
                                    ),
                                ),
                                (
                                    'controls',
                                    wagtail.core.blocks.BooleanBlock(
                                        default=True,
                                        help_text='Controls',
                                        required=False,
                                    ),
                                ),
                                (
                                    'block_media',
                                    wagtailmedia.blocks.AbstractMediaChooserBlock(
                                        null=True, required=False
                                    ),
                                ),
                                (
                                    'image',
                                    wagtail.images.blocks.ImageChooserBlock(
                                        null=True, required=False
                                    ),
                                ),
                                (
                                    'font_color',
                                    wagtail.core.blocks.CharBlock(
                                        null=True, required=False
                                    ),
                                ),
                                (
                                    'bg_color',
                                    wagtail.core.blocks.CharBlock(
                                        null=True, required=False
                                    ),
                                ),
                                (
                                    'text_align',
                                    wagtail.core.blocks.CharBlock(
                                        default='left', required=False
                                    ),
                                ),
                                (
                                    'text',
                                    wagtail.core.blocks.RichTextBlock(
                                        features=[
                                            'h1',
                                            'h2',
                                            'h3',
                                            'h4',
                                            'h5',
                                            'bold',
                                            'italic',
                                            'link',
                                            'document-link',
                                            'ol',
                                            'ul',
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    'button_link',
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                'font_color',
                                                wagtail.core.blocks.CharBlock(
                                                    null=True, required=False
                                                ),
                                            ),
                                            (
                                                'bg_color',
                                                wagtail.core.blocks.CharBlock(
                                                    null=True, required=False
                                                ),
                                            ),
                                            (
                                                'page_link',
                                                wagtail.core.blocks.PageChooserBlock(
                                                    help_text='Link to a page.',
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                'external_link',
                                                wagtail.core.blocks.URLBlock(
                                                    help_text='Link to a URL.',
                                                    label='Link URL',
                                                    max_length=200,
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                'text',
                                                wagtail.core.blocks.CharBlock(
                                                    help_text='Link text',
                                                    null=True,
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        null=True,
                                        required=False,
                                    ),
                                ),
                            ],
                            null=True,
                            required=False,
                        ),
                    )
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
