# Generated by Django 3.1 on 2020-10-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp657', '0059_auto_20201012_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formbirdpage',
            old_name='cover_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='searchbirdpage',
            old_name='cover_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='solobirdpage',
            old_name='cover_image',
            new_name='image',
        ),
    ]
