# Generated by Django 3.1 on 2020-11-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp657', '0061_auto_20201108_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='formbirdpage',
            name='hide_header',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchbirdpage',
            name='hide_header',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solobirdpage',
            name='hide_header',
            field=models.BooleanField(default=False),
        ),
    ]
