# Generated by Django 3.1 on 2020-11-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtaildocs', '0010_document_file_hash'),
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('birdapp657', '0062_auto_20201114_1804'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrandingSettings',
            new_name='BirdAppSettings',
        ),
    ]
