# Generated by Django 3.1 on 2021-01-30 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp657', '0065_auto_20210129_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solobirdpage',
            name='top_hero',
        ),
    ]
