# Generated by Django 4.0.5 on 2022-06-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp657', '0075_alter_solobirdpagetag_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='choices',
            field=models.TextField(
                blank=True,
                help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.',
                verbose_name='choices',
            ),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='default_value',
            field=models.TextField(
                blank=True,
                help_text='Default value. Comma or new line separated values supported for checkboxes.',
                verbose_name='default value',
            ),
        ),
    ]
