# Generated by Django 4.1.1 on 2022-09-17 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("birdapp657", "0076_alter_formfield_choices_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="birdappsettings",
            name="mobile_menu_page",
        ),
        migrations.DeleteModel(
            name="SearchBirdPage",
        ),
    ]
